#!/usr/bin/env bash
# Fetch the three real datasets used in the paper into ./datasets/.
# (The two synthetic datasets are generated by `python build_synth.py`.)
#
# Datasets:
#   - GloVe-100-angular   (ann-benchmarks)
#   - VK-LSVD             (HuggingFace: deepvk/VK-LSVD)
#   - YAMBDA              (HuggingFace: yandex/yambda)
#
# Requirements: curl, and `huggingface-cli` for VK-LSVD / YAMBDA
#   (`pip install -U "huggingface_hub[cli]"`)

set -euo pipefail
cd "$(dirname "$0")/.."

mkdir -p datasets/glove-100 datasets/vk-lsvd datasets/yambda

# --- GloVe-100-angular --------------------------------------------------------
if [ ! -f datasets/glove-100/glove-100-angular.hdf5 ]; then
  echo "[download] GloVe-100-angular..."
  curl -L -o datasets/glove-100/glove-100-angular.hdf5 \
    http://ann-benchmarks.com/glove-100-angular.hdf5
fi

# --- VK-LSVD ------------------------------------------------------------------
# We only need the item-embedding file; see https://huggingface.co/datasets/deepvk/VK-LSVD
if [ ! -f datasets/vk-lsvd/metadata/item_embeddings.npz ]; then
  echo "[download] VK-LSVD item embeddings..."
  huggingface-cli download deepvk/VK-LSVD \
    --repo-type dataset \
    --local-dir datasets/vk-lsvd \
    --include "metadata/item_embeddings.npz"
fi

# --- YAMBDA -------------------------------------------------------------------
# We only need the embeddings parquet; see https://huggingface.co/datasets/yandex/yambda
if [ ! -f datasets/yambda/embeddings.parquet ]; then
  echo "[download] YAMBDA embeddings..."
  huggingface-cli download yandex/yambda \
    --repo-type dataset \
    --local-dir datasets/yambda \
    --include "embeddings.parquet"
fi

echo "[done] Real datasets ready under ./datasets/"
echo "       Now generate synthetics:  python build_synth.py"
